---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c00
  namespace: argocd
spec:
  destination:
    name: decklor
    namespace: swift-config-ocp
  project: default
  source:
    path: c00
    repoURL: https://github.com/ben-obrien/ocp-config-ext
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
